#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May  1 21:53:40 2022

@author: joseph
"""

import numpy as np
import pandas as pd
import functions as funs

myData = funs.dataObject(covType = 'tot')